<?php

########################################################################
# Extension Manager/Repository config file for ext: "clubmanagement"
#
# Auto generated by Extension Builder 2012-08-09
#
# Manual updates:
# Only the data in the array - anything else is removed by next write.
# "version" and "dependencies" must not be touched!
########################################################################

$EM_CONF[$_EXTKEY] = array(
	'title' => 'Club Management',
	'description' => 'Manage seasons, teams with players, coaches and game reports',
	'category' => 'plugin',
	'author' => 'Thomas Löffler',
	'author_email' => 'loeffler@spooner-web.de',
	'author_company' => 'Spooner Web',
	'shy' => '',
	'priority' => '',
	'module' => '',
	'state' => 'alpha',
	'internal' => '',
	'uploadfolder' => '1',
	'createDirs' => '',
	'modify_tables' => '',
	'clearCacheOnLoad' => 0,
	'lockType' => '',
	'version' => '0.0.1',
	'constraints' => array(
		'depends' => array(
			'extbase' => '1.5',
			'fluid' => '1.5',
			'typo3' => '4.7',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);

?>